"use strict";
var nombre = "peter";
var numero = 123;
var booleano = true;
var hoy = new Date();
hoy = new Date('2020-10-21');
var cualquiera;
cualquiera = nombre;
cualquiera = numero;
cualquiera = booleano;
cualquiera = hoy;
